version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-users"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1recedy6xc1x3"
s3_prefix = "get-users"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

